services:
  # -------------------------------------------------------------
  # 1. DATABASE POSTGRESQL (Container Khusus Database)
  # -------------------------------------------------------------
  db:
    image: postgres:16-alpine
    container_name: api-sekolah-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: db_ragunan14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d db_ragunan14"]
      interval: 2s
      timeout: 5s
      retries: 10

  # -------------------------------------------------------------
  # 2. BACKEND API EXPRESS.JS (Container Khusus Aplikasi)
  # -------------------------------------------------------------
  api:
    build: .
    container_name: api-sekolah-app
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      PORT: 5000
      DATABASE_URL: "postgresql://postgres:password123@db:5432/db_ragunan14?schema=public"
    ports:
      - "5000:5000"

volumes:
  postgres_data:
    name: api_sekolah_postgres_data
