name: Deploy to School Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Pull Latest Code and Restart API
        run: |
          cd /var/www/api-sekolah
          git pull origin main
          npm install
          npx prisma migrate deploy
          npx prisma generate
          pm2 restart api-sekolah
