name: Deploy to School Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Pull Latest Code and Rebuild Docker Container
        run: |
          cd $HOME/apps/api-sekolah
          git pull origin main
          docker compose up -d --build
